### ISSUE TITLE
Implement logging in

### ISSUE THREAD

**Issue by TSkoll** [DoubleKilled/AnimeChanger#2]
Users should be allowed to log in through the program. This should be done through a "popup" window when user presses the "Log in" button in the main window. If no email/password combination is found the program should prompt the user to log in.

Login information should be kept in the program's appdata folder. Email can be saved as plaintext but password should be saved in as encrypted string for safety reasons.

This should be done before release.

**Comment by ghost** [comment]
I dun did it.

**Comment by TSkoll** [comment]
Implemented on [00b8242](https://github.com/DoubleKilled/AnimeChanger/commit/00b82423c87aa7563d7a76eaf863e89682169b59)
